# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/api/users/**
      - id: user-service-auth
        uri: lb://user-service
        predicates:
        - Path=/api/auth/**
      - id: order-service
        uri: lb://order-service
        predicates:
        - Path=/api/orders/**
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
